AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: HelloWorldLambdaJava

Resources:

  HelloWorldLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HelloWorldJava
      Runtime: java11
      MemorySize: 512
      Handler: book.EnvVarLambda::handler
      CodeUri: target/lambda.jar
      Timeout: 2
      Environment:
        Variables:
          ENV_VARIABLE: HelloEnv
